name: Deploy to Lolipop

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lolipop-deployment
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files by FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.LOLIPOP_FTP_SERVER }}
          username: ${{ secrets.LOLIPOP_FTP_USERNAME }}
          password: ${{ secrets.LOLIPOP_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /tools/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**